// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP1zygZdXegssdQwhHIzIgQ5IMXzoMKyQ',
    appId: '1:750119588253:android:c31fb6289cb52bcb101f74',
    messagingSenderId: '750119588253',
    projectId: 'teman-agro-admin',
    storageBucket: 'teman-agro-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0lQbKxlD1iyJFwrYYQ17Q6K0pZSf1T1k',
    appId: '1:750119588253:ios:b1ccba3cd908af6f101f74',
    messagingSenderId: '750119588253',
    projectId: 'teman-agro-admin',
    storageBucket: 'teman-agro-admin.appspot.com',
    androidClientId: '750119588253-46749n9bv2e3d5gri1e1ja7rsc2ll0q2.apps.googleusercontent.com',
    iosClientId: '750119588253-pb38vvl2sj2u77osfq8j7jcdqgjp1rdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.temanAgroAdmin',
  );
}
